import bpy

from bpy.types import Operator
from ..helper import sc_poll_op
from ..debug import log

class ScPrintStatistics(Operator):
    """Print the node tree statistics"""
    bl_idname = "sorcar.print_statistics"
    bl_label = "Print Statistics"

    @classmethod
    def poll(cls, context):
        return sc_poll_op(context)

    def execute(self, context):
        curr_tree = context.space_data.edit_tree
        if (curr_tree):
            # Cleanup objects that are generated by the procedural tree
            curr_tree.print_nodetree_stats()
            return {'FINISHED'}
        else:
            log("OPERATOR", None, self.bl_idname, "No current edit tree, operation cancelled", 1)
        return {'CANCELLED'}